<a href="https://colab.research.google.com/github/Parth354/Advocate-eportal/blob/main/first_ai_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing required Libraries For Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the Data Set

In [2]:
dataset=pd.read_csv('data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

Printing the Data

In [3]:
print(X)
print(Y)

[['Hcl' 18.74 4.14 53.26]
 ['Infosys' 26.09 8.2 56.69]
 ['Tcs' 28.32 12.48 111.0]
 ['Wipro' 16.65 3.79 20.71]
 ['Infosys' 30.38 9.18 56.69]
 ['Wipro' 20.12 3.47 20.71]
 ['Tcs' 32.1 14.15 111.0]
 ['Hcl' 22.42 4.97 53.26]]
['YES' 'NO' 'YES' 'YES' 'NO' 'NO' 'NO' 'NO']


Missing DATA

In [4]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [5]:
print(X)

[['Hcl' 18.74 4.14 53.26]
 ['Infosys' 26.09 8.2 56.69]
 ['Tcs' 28.32 12.48 111.0]
 ['Wipro' 16.65 3.79 20.71]
 ['Infosys' 30.38 9.18 56.69]
 ['Wipro' 20.12 3.47 20.71]
 ['Tcs' 32.1 14.15 111.0]
 ['Hcl' 22.42 4.97 53.26]]


Encoding Categorical Data


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 0.0 18.74 4.14 53.26]
 [0.0 1.0 0.0 0.0 26.09 8.2 56.69]
 [0.0 0.0 1.0 0.0 28.32 12.48 111.0]
 [0.0 0.0 0.0 1.0 16.65 3.79 20.71]
 [0.0 1.0 0.0 0.0 30.38 9.18 56.69]
 [0.0 0.0 0.0 1.0 20.12 3.47 20.71]
 [0.0 0.0 1.0 0.0 32.1 14.15 111.0]
 [1.0 0.0 0.0 0.0 22.42 4.97 53.26]]


Encoding Dependent Variables


In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

Splitting The Data into the training Data and Test Data

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2,random_state=1)


In [15]:
print(X_test)

[[1.0 0.0 0.0 0.0 22.42 4.97 53.26]
 [0.0 0.0 1.0 0.0 28.32 12.48 111.0]]


Feature Scaling


In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,4:]= sc.fit_transform(X_train[:,4:])
X_test[:,4:]=sc.transform(X_test[:,4:])

In [17]:
print(X_train)
print(X_test)

[[0.0 1.0 0.0 0.0 0.3531920265711554 0.27268806510014093
  0.11629133907572904]
 [0.0 0.0 1.0 0.0 1.3753512944809354 1.8253138903114712
  1.9139524278431372]
 [1.0 0.0 0.0 0.0 -0.8968696405065288 -0.7867507332793547
  0.0027583334695384714]
 [0.0 1.0 0.0 0.0 1.0828198567430278 0.5284146716055366
  0.11629133907572904]
 [0.0 0.0 0.0 1.0 -1.2523293526415438 -0.8780816641741388
  -1.074646719732066]
 [0.0 0.0 0.0 1.0 -0.6621641846470449 -0.9615842295636556
  -1.074646719732066]]
[[1.0 0.0 0.0 0.0 -0.27098842488123887 -0.5701659543002953
  0.0027583334695384714]
 [0.0 0.0 1.0 0.0 0.7324624371266977 1.3895348771849299
  1.9139524278431372]]
